import SiteHeader from "../components/SiteHeader";
import {industryProjects} from "../data/ecosystem";

const cases=[
  ["Polar Voyager","CHARACTER IP","1,024","/brand/aura-nft-01.jpg","Preserve character proportions while building an expedition series through environments, outfits and materials."],
  ["Neon City","COMMUNITY PFP","3,333","/brand/aura-nft-03.jpg","Build recognizable community avatars through lighting, districts and accessories."],
  ["Nature Spirit","BRAND COLLECTIBLE","1,000","/brand/aura-nft-08.jpg","Extend the brand's green visual language into nature themes and member collectibles."],
  ["Crystal Frontier","GAME ASSET","10,000","/brand/aura-nft-09.jpg","Build scalable character assets with equipment, regions and energy traits."],
] as const;
export default function Cases(){return <main><SiteHeader/><section className="sub-hero cases-hero"><span>COLLECTION STUDIES</span><h1>One subject. Multiple<br/><em>visual directions.</em></h1><p>AURA concept studies showing one recognizable character across distinct themes and use cases.</p><a href="/studio">Create my collection →</a></section><section className="case-showcase"><header><div><span>SELECTED DIRECTIONS</span><h2>AURA Collections</h2></div><p>Consistent subject · Controlled traits · Batch output</p></header><div className="case-page-grid">{cases.map((x,i)=><article key={x[0]}><div className="case-visual"><img src={x[3]} alt={x[0]}/><span>0{i+1}</span><b>{x[1]}</b></div><div className="case-copy"><small>{x[2]} ITEMS</small><h2>{x[0]}</h2><p>{x[4]}</p><a href="/studio">Use this direction <b>↗</b></a></div></article>)}</div><footer><b>What do these studies show?</b><p>AURA locks subject identity first, then treats backgrounds, materials, outfits and rarity as composable variables so collections can scale without losing recognition.</p><a href="/how-it-works">View the generation method →</a></footer></section><section className="reference-projects"><header><div><span>INDUSTRY REFERENCES</span><h2>NFT collections worth studying</h2></div><p>Public industry references, not AURA customers or partners.</p></header><div>{industryProjects.map(item=><a href={item.url} target="_blank" rel="noreferrer" key={item.name}><figure><img src={item.image} alt={`${item.name} project visual`}/><i>↗</i></figure><small>{item.category} · {item.count}</small><h3>{item.name}</h3><p>View the official project and public sources</p></a>)}</div></section></main>}
