"use client";

import {ChangeEvent,useEffect,useMemo,useState} from "react";
import JSZip from "jszip";
import {BrowserProvider,Contract,formatEther,isAddress} from "ethers";
import SiteHeader from "../components/SiteHeader";
import {useWallet} from "../components/WalletProvider";
import {AURA_COLLECTION_ABI,ROBINHOOD_CHAIN_ID,ROBINHOOD_EXPLORER} from "../lib/aura-contract";
import {markCreationMinted,readCreationHistory,saveCreationHistory} from "../lib/creation-history";

const studioSteps:Array<[number,string]>=[[1,"Define subject"],[2,"Generate & download"],[3,"Traits & Metadata"],[4,"Publish on Robinhood"]];

type Result={id:number;url:string;selected:boolean;rarity:string};
type SubjectCandidate={id:number;url:string};
type MintQuote={total:bigint};
type PublishResult={provider:string;imageUris:string[];tokenUris:string[];count:number;authorization?:{deadline:number;signature:string;nonce:string;totalPrice:string}};
type AiStatus={configured:boolean;provider:string;maxImages:number;batchSize?:number;outputSize?:string};
type AiGenerateResult={provider?:string;images?:string[];error?:string;message?:string};

async function appendPublishImages(form:FormData,items:Result[]){
  if(items.every(item=>/^https:\/\//i.test(item.url))){
    form.append("imageUrls",JSON.stringify(items.map(item=>item.url)));
    return;
  }
  for(let i=0;i<items.length;i++){
    const response=await fetch(items[i].url);
    if(!response.ok)throw new Error("IMAGE_DOWNLOAD_FAILED");
    const blob=await response.blob();
    form.append("images",new File([blob],`${String(i+1).padStart(4,"0")}.jpg`,{type:blob.type||"image/jpeg"}));
  }
}

async function requestAiImages(payload:{mode:"subject"|"collection";prompt:string;style:string;count:number;referenceImage?:string},onProgress?:(done:number,total:number)=>void){
  let lastError:Error|null=null;
  for(let attempt=0;attempt<2;attempt++){
    try{const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as AiGenerateResult;if(!response.ok||!result.images?.length){const error=new Error(result.message||result.error||"AI_GENERATION_FAILED");error.name=result.error||"AI_GENERATION_FAILED";throw error}const images=result.images.slice(0,payload.count);onProgress?.(images.length,payload.count);return images}
    catch(error){lastError=error instanceof Error?error:new Error("AI_GENERATION_FAILED");if(attempt===0)await new Promise(resolve=>setTimeout(resolve,900))}
  }
  throw lastError||new Error("AI_GENERATION_FAILED");
}

function aiFailureMessage(error:unknown,scope:"subject"|"collection"){
  const message=error instanceof Error?error.message:"AI_GENERATION_FAILED";
  const normalized=message.toLowerCase();
  if(normalized.includes("rate")||normalized.includes("429"))return "Image requests are busy. Wait a minute and retry.";
  if(normalized.includes("billing")||normalized.includes("balance")||normalized.includes("credit"))return "AURA image service is temporarily unavailable. Try again shortly.";
  if(normalized.includes("temporarily unavailable")||normalized.includes("service unavailable"))return "AURA image engine is busy. Try again shortly.";
  if(normalized.includes("timeout"))return `${scope}Generation timed out. Retry; incomplete requests are never written onchain.`;
  return `${scope === "subject" ? "Subject" : "Collection"} generation incomplete (${message.slice(0,120)}). Please try again shortly.`;
}

export default function Studio(){
  const {wallet,provider,connected,openWallets,ensureRobinhood}=useWallet();
  const [step,setStep]=useState(1);const [inputMode,setInputMode]=useState<"text"|"upload">("text");const [source,setSource]=useState("");const [fileName,setFileName]=useState("");const [subjectDescription,setSubjectDescription]=useState("");const [prompt,setPrompt]=useState("");const [style,setStyle]=useState("Pixel art");const [amount,setAmount]=useState("4");const [running,setRunning]=useState(false);const [results,setResults]=useState<Result[]>([]);const [subjectRunning,setSubjectRunning]=useState(false);const [subjectCandidates,setSubjectCandidates]=useState<SubjectCandidate[]>([]);const [chosenSubject,setChosenSubject]=useState<number|null>(null);const [subjectConfirmed,setSubjectConfirmed]=useState(false);
  const [aiStatus,setAiStatus]=useState<AiStatus|null>(null);const [aiError,setAiError]=useState("");const [subjectProgress,setSubjectProgress]=useState(0);const [generationProgress,setGenerationProgress]=useState(0);
  const [collection,setCollection]=useState("");const [symbol,setSymbol]=useState("");const [itemName,setItemName]=useState("");const [description,setDescription]=useState("");const [rarity,setRarity]=useState("Balanced");
  const [creationId,setCreationId]=useState("");
  const contractAddress=process.env.NEXT_PUBLIC_AURA_NFT_CONTRACT||"";const [chainStatus,setChainStatus]=useState("After connecting a wallet, AURA will prepare storage and contract access.");const [minting,setMinting]=useState(false);const [mintConfirmed,setMintConfirmed]=useState(false);const [showMarketGuide,setShowMarketGuide]=useState(false);const [checking,setChecking]=useState(false);const [publishing,setPublishing]=useState(false);const [published,setPublished]=useState<PublishResult|null>(null);const [txHash,setTxHash]=useState("");const [mintedTokenIds,setMintedTokenIds]=useState<number[]>([]);const [mintQuote,setMintQuote]=useState<MintQuote|null>(null);
  const contractVersion=process.env.NEXT_PUBLIC_AURA_NFT_CONTRACT_VERSION||"1";
  const selected=useMemo(()=>results.filter(x=>x.selected),[results]);
  const issuanceReady=Boolean(collection.trim()&&symbol.trim()&&itemName.trim()&&description.trim());
  const metadata=useMemo(()=>selected.map((x,i)=>({name:`${itemName} #${String(i+1).padStart(4,"0")}`,description,image:published?.imageUris[i]||"ipfs://AURA_UPLOAD_PENDING",attributes:[{trait_type:"Visual Style",value:style},{trait_type:"Variation",value:`V${x.id}`},{trait_type:"Rarity",value:x.rarity},{trait_type:"Rarity Model",value:rarity}]})),[selected,itemName,description,published,style,rarity]);
  useEffect(()=>{if(mintConfirmed)setShowMarketGuide(true)},[mintConfirmed]);
  useEffect(()=>{let active=true;fetch("/api/generate").then(response=>response.json()).then((status:AiStatus)=>{if(active)setAiStatus(status)}).catch(()=>{if(active)setAiStatus({configured:false,provider:"AURA",maxImages:4})});return()=>{active=false}},[]);
  useEffect(()=>{const restoreId=new URLSearchParams(window.location.search).get("restore");if(!restoreId)return;const record=readCreationHistory().find(item=>item.id===restoreId);if(!record)return;if(record.status==="minted"){window.location.replace("/history");return}const restored=record.assets?.length?record.assets:[{id:1,url:record.cover,selected:true,rarity:"Common"}];setCreationId(record.id);setCollection(record.collection||"");setPrompt(record.prompt||"");setStyle(record.style||"3D collectible");setAmount(String(Math.max(1,Math.min(4,restored.length))));setSource(record.cover||restored[0].url);setFileName(`${record.collection||"Untitled collection"}  · restored work`);setInputMode("upload");setSubjectConfirmed(true);setResults(restored.map(item=>({...item,selected:true})));if(record.symbol)setSymbol(record.symbol);if(record.itemName)setItemName(record.itemName);if(record.description)setDescription(record.description);if(record.rarityModel)setRarity(record.rarityModel);setPublished(null);setMintQuote(null);setChainStatus(`Restored ${restored.length}  works restored. Continue with metadata, IPFS upload and minting.`);setStep(2)},[]);
  useEffect(()=>{if(!showMarketGuide)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setShowMarketGuide(false)};window.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close)}},[showMarketGuide]);
  function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{setSource(String(reader.result));setFileName(file.name);setInputMode("upload");setSubjectCandidates([]);setChosenSubject(null);setSubjectConfirmed(true);setResults([]);setPublished(null);setMintQuote(null);setStep(1)};reader.readAsDataURL(file)}
  async function generateSubjects(){if(!subjectDescription.trim()||!aiStatus?.configured)return;setSubjectRunning(true);setSubjectProgress(0);setAiError("");setSubjectConfirmed(false);setChosenSubject(null);setResults([]);setPublished(null);setMintQuote(null);try{const images=await requestAiImages({mode:"subject",prompt:subjectDescription,style,count:1},done=>setSubjectProgress(done));setSubjectCandidates(images.map((url,index)=>({id:index+1,url})))}catch(error){setAiError(aiFailureMessage(error,"subject"))}finally{setSubjectRunning(false)}}
  function confirmSubject(){const candidate=subjectCandidates.find(x=>x.id===chosenSubject);if(!candidate)return;setSource(candidate.url);setFileName(`Text subject option ${candidate.id}`);setSubjectConfirmed(true);setResults([]);setPublished(null);setMintQuote(null)}
  async function generate(){if(!aiStatus?.configured||!prompt.trim()||(inputMode==="text"&&!subjectConfirmed)||(inputMode==="upload"&&!source))return;setRunning(true);setGenerationProgress(0);setAiError("");setPublished(null);setMintQuote(null);try{const direction=`${inputMode==="text"?subjectDescription:fileName}. ${prompt}`;const generationCount=Math.max(1,Math.min(4,Number(amount)||1));const images=await requestAiImages({mode:"collection",prompt:direction,style,count:generationCount,referenceImage:source},done=>setGenerationProgress(done));const variants:Result[]=images.map((url,index)=>({id:index+1,url,selected:true,rarity:index===images.length-1?"Legendary":index>Math.floor(images.length*.6)?"Rare":"Common"}));setResults(variants);const id=`aura-${Date.now()}`;setCreationId(id);saveCreationHistory({id,createdAt:Date.now(),wallet,collection,prompt:inputMode==="text"?subjectDescription:prompt,style,targetAmount:generationCount,previewCount:variants.length,cover:variants[0]?.url||source,status:"generated",assets:variants,symbol,itemName,description,rarityModel:rarity});setStep(2)}catch(error){setAiError(aiFailureMessage(error,"collection"))}finally{setRunning(false)}}
  function toggle(id:number){setMintQuote(null);setPublished(null);setResults(v=>v.map(x=>x.id===id?{...x,selected:!x.selected}:x))}
  function continueToMint(){
    if(!issuanceReady)return;
    if(creationId){const record=readCreationHistory().find(item=>item.id===creationId);if(record)saveCreationHistory({...record,collection:collection.trim(),symbol:symbol.trim(),itemName:itemName.trim(),description:description.trim(),rarityModel:rarity})}
    setStep(4);
  }
  async function saveZip(includeMetadata=false){const zip=new JSZip();for(let i=0;i<selected.length;i++){const blob=await(await fetch(selected[i].url)).blob();zip.file(`images/${String(i+1).padStart(4,"0")}.jpg`,blob)}if(includeMetadata){metadata.forEach((data,i)=>zip.file(`metadata/${String(i+1).padStart(4,"0")}.json`,JSON.stringify(data,null,2)));zip.file("collection.json",JSON.stringify({name:collection,symbol,chain:"Robinhood Mainnet",chainId:ROBINHOOD_CHAIN_ID,totalSupply:Number(amount),platformFee:0},null,2))}const blob=await zip.generateAsync({type:"blob"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=includeMetadata?`${symbol}-release-package.zip`:`${symbol}-images.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  async function publishAssets(){if(!wallet||!provider){openWallets();return null}if(!selected.length){setChainStatus("Select at least one generated result first.");return null}setPublishing(true);setPublished(null);setMintQuote(null);try{if(!await ensureRobinhood())throw new Error("WRONG_CHAIN");const ethersProvider=new BrowserProvider(provider);const signer=await ethersProvider.getSigner();const timestamp=Date.now();const message=`AURA IPFS Publish\nWallet:${wallet}\nCollection:${collection}\nTimestamp:${timestamp}`;const signature=await signer.signMessage(message);const form=new FormData();form.append("wallet",wallet);form.append("collection",collection);form.append("timestamp",String(timestamp));form.append("signature",signature);form.append("metadata",JSON.stringify(metadata.map(({name,description,attributes})=>({name,description,attributes}))));await appendPublishImages(form,selected);setChainStatus("AURA is uploading images and metadata to IPFS…");const response=await fetch("/api/publish",{method:"POST",body:form});const result=await response.json() as PublishResult&{error?:string;message?:string};if(!response.ok)throw new Error(result.message||result.error||"PUBLISH_FAILED");setPublished(result);setChainStatus(`${result.count}  images and metadata securely uploaded to IPFS by AURA`);return result}catch(e){const message=e instanceof Error?e.message:"";setChainStatus(message.includes("UPLOAD_NOT_CONFIGURED")||message.includes("STORAGE_NOT_CONFIGURED")?"AURA IPFS service is not configured. Contact the administrator.":message.includes("user rejected")||message.includes("ACTION_REJECTED")?"You cancelled the content publishing signature.":message.includes("WRONG_CHAIN")?"Wrong network: only Robinhood Mainnet (4663) is supported.":message.includes("REMOTE_IMAGE")?"Generated image could not be read. Regenerate or try again shortly.":"Upload incomplete. Check the files or try again shortly.");return null}finally{setPublishing(false)}}
  function validatePublish(currentPublished=published){if(!issuanceReady){setChainStatus("Complete the collection name, symbol, item name and description first.");return false}if(!isAddress(contractAddress)){setChainStatus("The official AURA Collection contract is not configured.");return false}if(!currentPublished||currentPublished.tokenUris.length!==selected.length){setChainStatus("Let AURA upload images and metadata first.");return false}if(contractVersion==="2"&&!currentPublished.authorization){setChainStatus("This batch is missing AURA mint authorization. Publish the assets again.");return false}if(!selected.length){setChainStatus("Select at least one generated result first.");return false}return true}
  function tokenUris(){return published?.tokenUris||[]}
  async function inspectMint(currentPublished=published){if(!wallet||!provider){openWallets();return null}if(!validatePublish(currentPublished))return null;setChecking(true);setMintQuote(null);try{if(!await ensureRobinhood())throw new Error("WRONG_CHAIN");const ethersProvider=new BrowserProvider(provider);const network=await ethersProvider.getNetwork();if(Number(network.chainId)!==ROBINHOOD_CHAIN_ID)throw new Error("WRONG_CHAIN");const code=await ethersProvider.getCode(contractAddress);if(code==="0x")throw new Error("NO_CONTRACT");const nft=new Contract(contractAddress,AURA_COLLECTION_ABI,ethersProvider);const total=BigInt(await nft.quoteMint(selected.length));const next={total};setMintQuote(next);setChainStatus(`Release ready: ${selected.length}  NFTs, mint value ${formatEther(total)} ETH, excluding network gas`);return next}catch(e){const message=e instanceof Error?e.message:"";setChainStatus(message.includes("WRONG_CHAIN")?"Wrong network: only Robinhood Mainnet (4663) is supported.":message.includes("NO_CONTRACT")?"No contract exists at this address on Robinhood Mainnet.":"Unable to read the contract quote. Confirm the verified AURA Collection contract.");return null}finally{setChecking(false)}}
  async function prepareMint(){const currentPublished=published||await publishAssets();if(currentPublished)await inspectMint(currentPublished)}
  async function mint(){if(!wallet||!provider){openWallets();return}if(!validatePublish())return;setMinting(true);setMintConfirmed(false);setTxHash("");setMintedTokenIds([]);try{if(!await ensureRobinhood())throw new Error("WRONG_CHAIN");const quote=await inspectMint();if(!quote)throw new Error("QUOTE_FAILED");const ethersProvider=new BrowserProvider(provider);const network=await ethersProvider.getNetwork();if(Number(network.chainId)!==ROBINHOOD_CHAIN_ID)throw new Error("WRONG_CHAIN");const signer=await ethersProvider.getSigner();const nft=new Contract(contractAddress,AURA_COLLECTION_ABI,signer);const authorization=published?.authorization;const tx=contractVersion==="2"&&authorization?await nft.mintBatchAuthorized(wallet,tokenUris(),authorization.deadline,authorization.signature,{value:quote.total}):await nft.mintBatch(wallet,tokenUris(),{value:quote.total});setTxHash(tx.hash);setChainStatus("Batch mint submitted. Waiting for Robinhood Mainnet confirmation.");const receipt=await tx.wait();const batchEvent=receipt?.logs.map((log:any)=>{try{return nft.interface.parseLog(log)}catch{return null}}).find((event:any)=>event?.name==="BatchMinted");if(batchEvent){const first=Number(batchEvent.args.firstTokenId??batchEvent.args[2]);const quantity=Number(batchEvent.args.quantity??batchEvent.args[3]);setMintedTokenIds(Array.from({length:quantity},(_,index)=>first+index))}if(creationId)markCreationMinted(creationId,tx.hash,wallet);setMintConfirmed(true);setChainStatus(`${selected.length}  NFTs minted on Robinhood Mainnet.`)}catch(e){const message=e instanceof Error?e.message:"";if(!message.includes("QUOTE_FAILED"))setChainStatus(message.includes("WRONG_CHAIN")?"Wrong network: only Robinhood Mainnet (4663) is supported.":message.includes("authorization expired")?"Mint authorization expired. Publish the assets again.":message.includes("invalid authorization")?"AURA mint authorization failed. Publish the assets again.":message.includes("user rejected")||message.includes("ACTION_REJECTED")?"You cancelled the transaction in your wallet.":"Mint incomplete. Check wallet balance, contract status, metadata URI and gas.")}finally{setMinting(false)}}
  const activeOperation=publishing?{step:"01",eyebrow:"SECURE ASSET STORAGE",title:"Writing images and metadata to IPFS",detail:"Approve the publishing signature in your wallet. AURA is creating immutable content addresses."}:checking?{step:"02",eyebrow:"SMART CONTRACT VERIFICATION",title:"Validating collection contract and mint value",detail:"Reading the Robinhood Mainnet contract, network and batch quote."}:minting?{step:"03",eyebrow:"ONCHAIN CONFIRMATION",title:"Waiting for wallet signature and onchain confirmation",detail:"The transaction will only be sent to Robinhood Mainnet. Keep this page open and do not switch networks."}:null;
  const mintPhase=mintConfirmed?"complete":!connected?"wallet":!mintQuote?"prepare":"mint";
  return <main className="studio-workspace"><SiteHeader/><section className="studio-top"><div><span>AURA Creation Engine</span><h1>Create your NFT Collection</h1><p>Generate, configure and publish from one workspace.</p></div><b><i/> ROBINHOOD MAINNET · 4663</b></section>
    <nav className="studio-steps">{studioSteps.map(x=><button className={step===x[0]?"active":step>x[0]?"done":""} key={x[0]} onClick={()=>step>=x[0]&&setStep(x[0])}><i>{step>x[0]?"✓":x[0]}</i><span>{x[1]}</span></button>)}</nav>
    <section className="studio-stage">
      {activeOperation&&<div className="chain-operation" role="status" aria-live="polite"><div className="operation-orbit"><i/><i/><i/><b>{activeOperation.step}</b></div><div className="operation-copy"><small>{activeOperation.eyebrow}</small><strong>{activeOperation.title}</strong><p>{activeOperation.detail}</p><div className="operation-progress"><i/></div></div></div>}
      {!activeOperation&&mintConfirmed&&step===4&&<div className="transaction-ready"><i>✓</i><div><b>Mint complete. Assets are recorded on Robinhood Mainnet.</b><small>{chainStatus}</small></div><a href="/history">View my onchain works and records →</a><span>ROBINHOOD MAINNET</span></div>}
      {step===1&&<div className="stage-input">
        <aside><span>01 · Subject</span><h2>Describe or upload a subject</h2><div className="source-tabs"><button className={inputMode==="text"?"active":""} onClick={()=>setInputMode("text")}>Text prompt</button><button className={inputMode==="upload"?"active":""} onClick={()=>setInputMode("upload")}>Upload image</button></div>{inputMode==="text"?<div className="source-description"><label>Subject description<textarea value={subjectDescription} onChange={e=>{setSubjectDescription(e.target.value);setSubjectConfirmed(false)}} maxLength={300} placeholder="Example: a rounded non-human AURA Wisp with a dark visor, mint-green eyes and a star core"/><small>{subjectDescription.length}/300</small></label><button className="subject-generate" onClick={generateSubjects} disabled={!aiStatus?.configured||subjectRunning||!subjectDescription.trim()}>{!aiStatus?"Connecting…":!aiStatus.configured?"Engine unavailable":subjectRunning?`AURA is generating · ${subjectProgress}/1`:"Generate subject"} <b>→</b></button>{subjectCandidates.length>0&&<><div className="subject-candidates" aria-label="Subject candidates">{subjectCandidates.map(candidate=><button className={chosenSubject===candidate.id?"selected":""} onClick={()=>{setChosenSubject(candidate.id);setSubjectConfirmed(false)}} key={candidate.id}><img src={candidate.url} alt="Generated subject preview"/><span>Subject preview</span></button>)}</div><div className="subject-confirm"><span>{subjectConfirmed?"✓ Subject confirmed":chosenSubject?"Use this subject for the collection":"Select subject"}</span><button onClick={confirmSubject} disabled={!chosenSubject||subjectConfirmed}>{subjectConfirmed?"Confirmed":"Confirm subject"}</button></div></>}</div>:<label className={`source-upload ${source?"has-image":"empty"}`} style={{backgroundImage:source?`url(${source})`:"none"}}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/>{!source&&<span className="upload-empty-mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 16V5m0 0L8 9m4-4 4 4M5 14v4a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-4"/></svg></span>}<b>{source?"Replace image":"Choose subject image"}</b><small>{fileName||"PNG, JPG or WEBP · square recommended"}</small></label>}<p>{inputMode==="text"?"Generate and approve one subject before expanding the collection.":"A clear subject on a simple background works best."}</p></aside>
        <article><span>02 · Collection direction</span><h2>Generate collection variants</h2><div className={`ai-provider ${aiStatus?.configured?"online":"offline"}`}><i/><div><b>{aiStatus?.configured?"AURA image engine connected":aiStatus===null?"Connecting to AURA image engine":"AURA image engine unavailable"}</b></div><em>{aiStatus?.configured?"READY":"OFFLINE"}</em></div>{aiError&&<div className="ai-error" role="alert"><b>Generation incomplete</b><span>{aiError}</span><button onClick={()=>setAiError("")}>×</button></div>}<label>Creative direction<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={500} placeholder="Example: preserve the Wisp silhouette, visor proportions and star core while varying gear, materials, lighting and worlds"/><small>{prompt.length}/500</small></label><div className="studio-fields"><label>Visual style<select value={style} onChange={e=>setStyle(e.target.value)}><option>3D collectible</option><option>PFP portrait</option><option>Pixel art</option><option>Brand illustration</option></select></label><label>Output count<select value={amount} onChange={e=>setAmount(String(Math.max(1,Math.min(4,Number(e.target.value)||1))))}><option value="1">1 image</option><option value="2">2 images</option><option value="3">3 images</option><option value="4">4 images · current limit</option><option disabled>50 images · coming soon</option><option disabled>100 images · coming soon</option><option disabled>500 images · coming soon</option><option disabled>1,000 images · coming soon</option><option disabled>3,333 images · coming soon</option></select></label></div><p className="scale-note"><b>Small-batch testing only.</b> Large collections require longer processing time. Output sizes from 50 to 3,333 images are not yet available.</p><button className="stage-primary" onClick={generate} disabled={!aiStatus?.configured||running||!prompt.trim()||(inputMode==="text"&&!subjectConfirmed)||(inputMode==="upload"&&!source)}>{!aiStatus?"Connecting…":!aiStatus.configured?"Image engine unavailable":running?`AURA is generating · ${generationProgress}/${amount}`:inputMode==="upload"&&!source?"Upload a subject image first":inputMode==="text"&&!subjectConfirmed?"Approve the subject first":!prompt.trim()?"Add a creative direction":`Generate ${amount}  collection images →`}</button><p className="engine-note">Lock the subject identity, then expand outfits, accessories, materials, scenes and rarity traits.</p></article>
      </div>}
      {step===2&&<div className="stage-results"><header><div><span>GENERATED OUTPUT</span><h2>Select collection images</h2><p>Click an image to select or deselect. Selected  {selected.length} / {results.length}  directions.</p></div><button onClick={()=>saveZip(false)}>↓ Download image ZIP</button></header><div>{results.map(x=><button className={x.selected?"selected":""} onClick={()=>toggle(x.id)} key={x.id}><img src={x.url} alt={`Generated variant ${x.id}`}/><span><i>{x.selected?"✓":"+"}</i> V{x.id} · {x.rarity}</span></button>)}</div><footer><button onClick={()=>setStep(1)}>← Back to edit</button><button className="stage-primary" disabled={!selected.length} onClick={()=>setStep(3)}>Next: Configure traits and metadata →</button></footer></div>}
      {step===3&&<div className="metadata-stage"><aside><span>COLLECTION SETTINGS</span><h2>Collection identity</h2><label>Collection name<input value={collection} placeholder="Example: AURA Genesis" onChange={e=>{setCollection(e.target.value);setPublished(null);setMintQuote(null)}}/></label><div className="studio-fields"><label>Symbol<input value={symbol} placeholder="Example: AURA" onChange={e=>{setSymbol(e.target.value.toUpperCase().slice(0,8));setPublished(null);setMintQuote(null)}}/></label><label>Item name prefix<input value={itemName} placeholder="Example: AURA Explorer" onChange={e=>{setItemName(e.target.value);setPublished(null);setMintQuote(null)}}/></label></div><label>Collection description<textarea value={description} placeholder="Describe the collection theme, story or purpose" onChange={e=>{setDescription(e.target.value);setPublished(null);setMintQuote(null)}}/></label><p className="metadata-required">Examples are not written onchain. Enter your publishing details.</p><label>Rarity model<select value={rarity} onChange={e=>{setRarity(e.target.value);setPublished(null);setMintQuote(null)}}><option value="Balanced">Balanced distribution</option><option value="Collector">Collectible: fewer rare traits</option><option value="Game">Game: multi-level traits</option></select></label><button className="package-btn" disabled={!issuanceReady} onClick={()=>saveZip(true)}>↓ Download release package</button></aside><article><header><span>METADATA PREVIEW</span><b>{metadata.length} JSON FILES</b></header><pre>{issuanceReady?JSON.stringify(metadata[0]||{},null,2):"Complete the collection details to preview Metadata"}</pre><div className="metadata-checks"><p><i>✓</i> Images mapped to token IDs</p><p><i>✓</i> Traits and rarity validated</p><p><i>✓</i> Standard JSON output</p></div><footer><button onClick={()=>setStep(2)}>← Back to selection</button><button className="stage-primary" disabled={!issuanceReady} onClick={continueToMint}>{issuanceReady?"Next: Publish on Robinhood →":"Complete collection details first"}</button></footer></article></div>}
      {step===4&&<div className="mint-stage mint-console">
        <aside><span>COLLECTION REVIEW</span><div className="mint-review-title"><div><h2>{collection}</h2><small>{symbol} · {selected.length} ITEMS</small></div><b>READY</b></div><div className="mint-cover"><img src={selected[0]?.url||source} alt="collection cover"/><div><b>{selected.length}  works selected</b><small>Images, traits and metadata mapped</small></div></div><div className="mint-preview-strip">{selected.slice(0,5).map(item=><img src={item.url} alt="" key={item.id}/>)}{selected.length>5&&<i>+{selected.length-5}</i>}</div><dl><div><dt>Publishing network</dt><dd><i className="status-dot"/> Robinhood Mainnet</dd></div><div><dt>Official collection</dt><dd>AURA Official Collection</dd></div><div><dt>Contract</dt><dd>{contractAddress?`${contractAddress.slice(0,8)}…${contractAddress.slice(-6)}`:"Waiting for configuration"}</dd></div><div><dt>Platform fee</dt><dd>0 ETH</dd></div><div><dt>Asset storage</dt><dd>{published?`${published.count} items · IPFS`:"Not published"}</dd></div></dl><button className="mint-back" onClick={()=>setStep(3)}>← Back to metadata settings</button></aside>
        <article><div className="mint-console-head"><div><span>ONCHAIN PUBLISHER</span><h2>Publish to Robinhood Mainnet</h2></div><b><i/> MAINNET · 4663</b></div><p>Authorize and publish directly from your wallet.</p><div className="mint-assurances"><span><i>01</i><b>Content signature</b><small>No gas required</small></span><span><i>02</i><b>Mint signature</b><small>Pay network gas</small></span><span><i>0</i><b>Platform fee</b><small>0 ETH</small></span></div><div className="mint-flow-list"><div className={published?"done":mintPhase==="wallet"||mintPhase==="prepare"?"active":""}><i>{published?"✓":"01"}</i><span><b>Permanent asset storage</b><small>{published?"IPFS · Complete":connected?"Waiting for content signature":"Waiting for wallet connection"}</small></span></div><div className={mintQuote?"done":mintPhase==="prepare"&&published?"active":""}><i>{mintQuote?"✓":"02"}</i><span><b>Contract and fee validation</b><small>{mintQuote?`This batch: ${formatEther(mintQuote.total)} ETH` :published?"Reading mint value":"Validated automatically after upload"}</small></span></div><div className={mintConfirmed?"done":mintPhase==="mint"?"active":""}><i>{mintConfirmed?"✓":"03"}</i><span><b>Wallet signature and mint</b><small>{mintConfirmed?"Robinhood Mainnet Confirmed":txHash?"Waiting for block confirmation":"One signature completes the batch mint"}</small></span></div></div>
          <div className="mint-wallet-row"><div><i className={connected?"online":""}/><span><small>Publishing wallet</small><b>{connected?`${wallet.slice(0,8)}…${wallet.slice(-6)}`:"Not connected"}</b></span></div><button onClick={openWallets}>{connected?"Manage wallet":"Connect wallet"}</button></div>
          {mintQuote&&<div className="mint-quote"><div><span>NFT mint value</span><b>{formatEther(mintQuote.total)} ETH</b></div><div><span>AURA platform fee</span><b>0 ETH</b></div><div><span>Wallet payment (excluding gas)</span><b>{formatEther(mintQuote.total)} ETH</b></div></div>}
          <div className={`mint-status-panel ${mintConfirmed?"success":""}`}><i>{mintConfirmed?"✓":"i"}</i><span><b>{mintConfirmed?"Onchain publishing complete":txHash?"Transaction pending":"Current status"}</b><small>{chainStatus}</small></span></div>
          <div className="mint-primary-zone">{mintPhase==="wallet"?<button className="mint-unified-action" onClick={openWallets}>Connect wallet to begin publishing <b>→</b></button>:mintPhase==="prepare"?<button className="mint-unified-action" onClick={prepareMint} disabled={publishing||checking}>{publishing?"Uploading images and metadata…":checking?"Validating official contract and fees…":published?"Revalidate publishing setup":"Prepare onchain publishing"} <b>→</b></button>:mintPhase==="mint"?<button className="mint-unified-action mint-now" onClick={mint} disabled={minting||checking}>{minting?"Waiting for wallet and onchain confirmation…":`Confirm mint ${selected.length}  NFTs`} <b>→</b></button>:<a className="mint-unified-action mint-complete" href="/history">View published collection <b>→</b></a>}</div>
          {txHash?<div className="mint-result-links"><a href={`${ROBINHOOD_EXPLORER}/tx/${txHash}`} target="_blank" rel="noreferrer">View transaction ↗</a><a href="/history">Open my onchain records →</a></div>:<small className="mint-warning">Your wallet only requests signatures required for the current step. Robinhood calculates gas in real time.</small>}
        </article>
      </div>}
    </section>
    {showMarketGuide&&mintConfirmed&&<div className="post-mint-market" role="dialog" aria-modal="true" aria-labelledby="post-mint-title">
      <section>
        <button className="post-mint-close" onClick={()=>setShowMarketGuide(false)} aria-label="Close OpenSea listing guide">×</button>
        <div className="post-mint-visual"><div className="mint-success-ring"><i>✓</i><span/><span/></div><small>TRANSACTION CONFIRMED</small><b>ROBINHOOD<br/>MAINNET</b><code>{txHash?`${txHash.slice(0,10)}…${txHash.slice(-8)}`:"CONFIRMED"}</code></div>
        <div className="post-mint-copy">
          <span className="post-mint-kicker"><i/> MINT SUCCESS · NEXT STEP</span>
          <h2 id="post-mint-title">NFTs minted successfully.<br/>Open  <em>OpenSea</em>  for listing?</h2>
          <p>Your  <strong>{selected.length}  NFTs</strong>  now belong to this wallet. Open the minted asset directly; OpenSea profile totals can take several minutes to update.</p>
          <div className="market-guide-steps"><article><i>1</i><span><b>Connect the same wallet</b><small>Use the wallet from this mint:  {wallet?`${wallet.slice(0,7)}…${wallet.slice(-5)}`:"Wallet"}</small></span></article><article><i>2</i><span><b>Open the minted asset</b><small>The direct asset page does not depend on profile aggregation.</small></span></article><article><i>3</i><span><b>Set a price and sign the listing.</b><small>Pricing, royalties and marketplace fees follow OpenSea terms</small></span></article></div>
          <div className="post-mint-actions"><a className="market-primary" href={mintedTokenIds.length&&contractAddress?`https://opensea.io/item/robinhood/${contractAddress.toLowerCase()}/${mintedTokenIds[0]}`:"https://opensea.io/collection/aura-collection-888849063"} target="_blank" rel="noopener noreferrer"><span className="opensea-mark">OS</span><b>View minted NFT on OpenSea</b><i>↗</i></a><a href="/history">View all minted works <b>→</b></a></div>
          <div className="post-mint-links">{txHash&&<a href={`${ROBINHOOD_EXPLORER}/tx/${txHash}`} target="_blank" rel="noreferrer">Verify this transaction ↗</a>}<button onClick={()=>setShowMarketGuide(false)}>Not now</button></div>
          <small className="market-disclaimer">OpenSea is a third-party marketplace. AURA never lists automatically or takes custody; your wallet controls listing and signing.</small>
        </div>
      </section>
    </div>}
  </main>
}
