"use client";

import {ChangeEvent,useEffect,useMemo,useState} from "react";
import JSZip from "jszip";
import {BrowserProvider,Contract,formatEther,isAddress} from "ethers";
import SiteHeader from "../components/SiteHeader";
import {useWallet} from "../components/WalletProvider";
import {AURA_COLLECTION_ABI,ROBINHOOD_CHAIN_ID,ROBINHOOD_EXPLORER} from "../lib/aura-contract";
import {markCreationMinted,readCreationHistory,saveCreationHistory} from "../lib/creation-history";

const filters=["saturate(1.08) hue-rotate(0deg)","saturate(1.25) hue-rotate(22deg)","contrast(1.08) hue-rotate(52deg)","saturate(.82) hue-rotate(105deg)","contrast(1.14) hue-rotate(160deg)","saturate(1.3) hue-rotate(205deg)","contrast(1.06) hue-rotate(255deg)","saturate(1.15) hue-rotate(310deg)"];
const palettes=[["#dffaf0","#64dcb0"],["#e9e5ff","#8e7cf4"],["#e2f4ff","#55b8ed"],["#fff0df","#ef9a62"],["#e8f7df","#8bc46b"],["#ffe4ef","#e779a4"],["#e5e8ff","#6578dc"],["#f6f2d9","#d6bd57"]];
const studioSteps:Array<[number,string]>=[[1,"输入主体"],[2,"生成与下载"],[3,"属性与 Metadata"],[4,"Robinhood 上链"]];

type Result={id:number;url:string;selected:boolean;rarity:string};
type SubjectCandidate={id:number;url:string};
type MintQuote={total:bigint};
type PublishResult={provider:string;imageUris:string[];tokenUris:string[];count:number;authorization?:{deadline:number;signature:string;nonce:string;totalPrice:string}};
type AiStatus={configured:boolean;provider:string;model:string;maxImages:number;batchSize?:number};
type AiGenerateResult={provider?:string;model?:string;images?:string[];error?:string;message?:string};

async function appendPublishImages(form:FormData,items:Result[]){
  if(items.every(item=>/^https:\/\//i.test(item.url))){
    form.append("imageUrls",JSON.stringify(items.map(item=>item.url)));
    return;
  }
  for(let i=0;i<items.length;i++){
    const response=await fetch(items[i].url);
    if(!response.ok)throw new Error("IMAGE_DOWNLOAD_FAILED");
    const blob=await response.blob();
    form.append("images",new File([blob],`${String(i+1).padStart(4,"0")}.jpg`,{type:blob.type||"image/jpeg"}));
  }
}

function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
async function createVariants(source:string,prompt:string){
  const img=await loadImage(source);const seed=[...prompt].reduce((a,c)=>a+c.charCodeAt(0),0);
  return Promise.all(filters.map(async(filter,i)=>{const canvas=document.createElement("canvas");canvas.width=768;canvas.height=768;const ctx=canvas.getContext("2d")!;const colors=palettes[(i+seed)%palettes.length];const bg=ctx.createLinearGradient(0,0,768,768);bg.addColorStop(0,colors[0]);bg.addColorStop(1,colors[1]);ctx.fillStyle=bg;ctx.fillRect(0,0,768,768);const scale=Math.max(768/img.width,768/img.height);const w=img.width*scale,h=img.height*scale;ctx.save();ctx.globalAlpha=.93;ctx.filter=filter;ctx.drawImage(img,(768-w)/2,(768-h)/2,w,h);ctx.restore();const glow=ctx.createRadialGradient(580,150,0,580,150,330);glow.addColorStop(0,"rgba(255,255,255,.42)");glow.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=glow;ctx.fillRect(0,0,768,768);ctx.fillStyle="rgba(8,22,18,.72)";ctx.fillRect(26,698,130,38);ctx.fillStyle="#fff";ctx.font="600 16px Arial";ctx.fillText(`AURA  #${String(i+1).padStart(3,"0")}`,42,723);return {id:i+1,url:canvas.toDataURL("image/jpeg",.9),selected:true,rarity:i===7?"Legendary":i>4?"Rare":"Common"} as Result}))
}

async function requestSingleAiImage(payload:{mode:"subject"|"collection";prompt:string;style:string;referenceImage?:string}){
  let lastError:Error|null=null;
  for(let attempt=0;attempt<2;attempt++){
    try{const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,count:1})});const result=await response.json() as AiGenerateResult;if(!response.ok||!result.images?.length){const error=new Error(result.message||result.error||"AI_GENERATION_FAILED");error.name=result.error||"AI_GENERATION_FAILED";throw error}return result.images[0]}
    catch(error){lastError=error instanceof Error?error:new Error("AI_GENERATION_FAILED");if(attempt===0)await new Promise(resolve=>setTimeout(resolve,900))}
  }
  throw lastError||new Error("AI_GENERATION_FAILED");
}

async function requestAiImages(payload:{mode:"subject"|"collection";prompt:string;style:string;count:number;referenceImage?:string},onProgress?:(done:number,total:number)=>void){
  const images=new Array<string>(payload.count);let cursor=0;let completed=0;
  const worker=async()=>{while(cursor<payload.count){const index=cursor++;const variation=payload.mode==="subject"?`候选主体 ${index+1}/${payload.count}：采用独立且有辨识度的轮廓与细节方向。`:`系列变体 ${index+1}/${payload.count}：使用独特的服装、材质、配件、光线和环境组合。`;images[index]=await requestSingleAiImage({...payload,prompt:`${payload.prompt}\n${variation}`});completed++;onProgress?.(completed,payload.count)}};
  // QuickRouter image edits are long-running requests. Keep them sequential so
  // local/system proxies do not reset concurrent multipart connections.
  await worker();
  return images;
}

function aiFailureMessage(error:unknown,scope:"主体"|"系列"){
  const message=error instanceof Error?error.message:"AI_GENERATION_FAILED";
  const normalized=message.toLowerCase();
  if(normalized.includes("rate")||normalized.includes("429"))return "图片服务请求较多，请稍等一分钟后重试。";
  if(normalized.includes("billing")||normalized.includes("balance")||normalized.includes("credit"))return "图片服务商账户余额不足或计费状态异常，请管理员检查 QuickRouter 账户。";
  if(normalized.includes("temporarily unavailable")||normalized.includes("service unavailable"))return "QuickRouter 图片模型当前繁忙，系统已经自动重试。请稍等一至两分钟后再次生成。";
  if(normalized.includes("timeout"))return `${scope}生成等待超时，请重新生成；已经完成的请求不会写入链上。`;
  return `${scope}生成未完成（${message.slice(0,120)}）。请稍后重新尝试。`;
}

export default function Studio(){
  const {wallet,provider,connected,openWallets,ensureRobinhood}=useWallet();
  const [step,setStep]=useState(1);const [inputMode,setInputMode]=useState<"text"|"upload">("text");const [source,setSource]=useState("/brand/aura-nft-01.jpg");const [fileName,setFileName]=useState("AURA Wisp 示例主体");const [subjectDescription,setSubjectDescription]=useState("一只圆润的非人类 AURA 能量精灵，深色面罩、薄荷绿双眼与胸前星芒核心");const [prompt,setPrompt]=useState("保持精灵轮廓、面罩比例与星芒核心，扩展不同装备、材质、光线和世界场景");const [style,setStyle]=useState("像素艺术");const [amount,setAmount]=useState("4");const [running,setRunning]=useState(false);const [results,setResults]=useState<Result[]>([]);const [subjectRunning,setSubjectRunning]=useState(false);const [subjectCandidates,setSubjectCandidates]=useState<SubjectCandidate[]>([]);const [chosenSubject,setChosenSubject]=useState<number|null>(null);const [subjectConfirmed,setSubjectConfirmed]=useState(false);
  const [aiStatus,setAiStatus]=useState<AiStatus|null>(null);const [aiError,setAiError]=useState("");const [subjectProgress,setSubjectProgress]=useState(0);const [generationProgress,setGenerationProgress]=useState(0);
  const [collection,setCollection]=useState("AURA Genesis");const [symbol,setSymbol]=useState("AURA");const [itemName,setItemName]=useState("AURA Explorer");const [description,setDescription]=useState("由 AURA Collection Engine 生成的链上数字收藏系列。");const [rarity,setRarity]=useState("Balanced");
  const [creationId,setCreationId]=useState("");
  const contractAddress=process.env.NEXT_PUBLIC_AURA_NFT_CONTRACT||"";const [chainStatus,setChainStatus]=useState("连接钱包后，AURA 将自动准备存储与合约");const [minting,setMinting]=useState(false);const [mintConfirmed,setMintConfirmed]=useState(false);const [showMarketGuide,setShowMarketGuide]=useState(false);const [checking,setChecking]=useState(false);const [publishing,setPublishing]=useState(false);const [published,setPublished]=useState<PublishResult|null>(null);const [txHash,setTxHash]=useState("");const [mintQuote,setMintQuote]=useState<MintQuote|null>(null);
  const contractVersion=process.env.NEXT_PUBLIC_AURA_NFT_CONTRACT_VERSION||"1";
  const selected=useMemo(()=>results.filter(x=>x.selected),[results]);
  const metadata=useMemo(()=>selected.map((x,i)=>({name:`${itemName} #${String(i+1).padStart(4,"0")}`,description,image:published?.imageUris[i]||"ipfs://AURA_UPLOAD_PENDING",attributes:[{trait_type:"Visual Style",value:style},{trait_type:"Variation",value:`V${x.id}`},{trait_type:"Rarity",value:x.rarity},{trait_type:"Rarity Model",value:rarity}]})),[selected,itemName,description,published,style,rarity]);
  useEffect(()=>{if(mintConfirmed)setShowMarketGuide(true)},[mintConfirmed]);
  useEffect(()=>{let active=true;fetch("/api/generate").then(response=>response.json()).then((status:AiStatus)=>{if(active)setAiStatus(status)}).catch(()=>{if(active)setAiStatus({configured:false,provider:"AI",model:"gpt-image-2.5-sunburst",maxImages:8})});return()=>{active=false}},[]);
  useEffect(()=>{const restoreId=new URLSearchParams(window.location.search).get("restore");if(!restoreId)return;const record=readCreationHistory().find(item=>item.id===restoreId);if(!record)return;const restored=record.assets?.length?record.assets:[{id:1,url:record.cover,selected:true,rarity:"Common"}];setCreationId(record.id);setCollection(record.collection||"AURA Collection");setPrompt(record.prompt||"");setStyle(record.style||"3D 收藏品");setAmount(String(Math.max(1,Math.min(4,restored.length))));setSource(record.cover||restored[0].url);setFileName(`${record.collection||"AURA"} · 已恢复作品`);setInputMode("upload");setSubjectConfirmed(true);setResults(restored.map(item=>({...item,selected:true})));if(record.symbol)setSymbol(record.symbol);if(record.itemName)setItemName(record.itemName);if(record.description)setDescription(record.description);if(record.rarityModel)setRarity(record.rarityModel);setPublished(null);setMintQuote(null);setChainStatus(`已恢复 ${restored.length} 件作品，可继续配置 Metadata、上传 IPFS 并 Mint`);setStep(2)},[]);
  useEffect(()=>{if(!showMarketGuide)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setShowMarketGuide(false)};window.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close)}},[showMarketGuide]);
  function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{setSource(String(reader.result));setFileName(file.name);setInputMode("upload");setSubjectCandidates([]);setChosenSubject(null);setSubjectConfirmed(true);setResults([]);setPublished(null);setMintQuote(null);setStep(1)};reader.readAsDataURL(file)}
  async function generateSubjects(){if(!subjectDescription.trim())return;setSubjectRunning(true);setSubjectProgress(0);setAiError("");setSubjectConfirmed(false);setChosenSubject(null);setResults([]);setPublished(null);setMintQuote(null);try{if(aiStatus?.configured){const images=await requestAiImages({mode:"subject",prompt:subjectDescription,style,count:1},done=>setSubjectProgress(done));setSubjectCandidates(images.map((url,index)=>({id:index+1,url})))}else{const variants=await createVariants("/brand/aura-nft-01.jpg",subjectDescription);setSubjectCandidates(variants.slice(0,1).map(({id,url})=>({id,url})))}}catch(error){setAiError(aiFailureMessage(error,"主体"))}finally{setSubjectRunning(false)}}
  function confirmSubject(){const candidate=subjectCandidates.find(x=>x.id===chosenSubject);if(!candidate)return;setSource(candidate.url);setFileName(`文字主体方案 ${candidate.id}`);setSubjectConfirmed(true);setResults([]);setPublished(null);setMintQuote(null)}
  async function generate(){if(inputMode==="text"&&!subjectConfirmed)return;setRunning(true);setGenerationProgress(0);setAiError("");setPublished(null);setMintQuote(null);try{let variants:Result[];const direction=`${inputMode==="text"?subjectDescription:fileName}. ${prompt}`;const generationCount=Math.max(1,Math.min(4,Number(amount)||1));if(aiStatus?.configured){const images=await requestAiImages({mode:"collection",prompt:direction,style,count:generationCount,referenceImage:source},done=>setGenerationProgress(done));variants=images.map((url,index)=>({id:index+1,url,selected:true,rarity:index===images.length-1?"Legendary":index>Math.floor(images.length*.6)?"Rare":"Common"}))}else{variants=(await createVariants(source,direction)).slice(0,generationCount)}setResults(variants);const id=`aura-${Date.now()}`;setCreationId(id);saveCreationHistory({id,createdAt:Date.now(),wallet,collection,prompt:inputMode==="text"?subjectDescription:prompt,style,targetAmount:generationCount,previewCount:variants.length,cover:variants[0]?.url||source,status:"generated",assets:variants,symbol,itemName,description,rarityModel:rarity});setStep(2)}catch(error){setAiError(aiFailureMessage(error,"系列"))}finally{setRunning(false)}}
  function toggle(id:number){setMintQuote(null);setPublished(null);setResults(v=>v.map(x=>x.id===id?{...x,selected:!x.selected}:x))}
  async function saveZip(includeMetadata=false){const zip=new JSZip();for(let i=0;i<selected.length;i++){const blob=await(await fetch(selected[i].url)).blob();zip.file(`images/${String(i+1).padStart(4,"0")}.jpg`,blob)}if(includeMetadata){metadata.forEach((data,i)=>zip.file(`metadata/${String(i+1).padStart(4,"0")}.json`,JSON.stringify(data,null,2)));zip.file("collection.json",JSON.stringify({name:collection,symbol,chain:"Robinhood Mainnet",chainId:ROBINHOOD_CHAIN_ID,totalSupply:Number(amount),platformFee:0},null,2))}const blob=await zip.generateAsync({type:"blob"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=includeMetadata?`${symbol}-发行包.zip`:`${symbol}-图片.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  async function publishAssets(){if(!wallet||!provider){openWallets();return null}if(!selected.length){setChainStatus("请先选择至少一件生成结果");return null}setPublishing(true);setPublished(null);setMintQuote(null);try{if(!await ensureRobinhood())throw new Error("WRONG_CHAIN");const ethersProvider=new BrowserProvider(provider);const signer=await ethersProvider.getSigner();const timestamp=Date.now();const message=`AURA IPFS Publish\nWallet:${wallet}\nCollection:${collection}\nTimestamp:${timestamp}`;const signature=await signer.signMessage(message);const form=new FormData();form.append("wallet",wallet);form.append("collection",collection);form.append("timestamp",String(timestamp));form.append("signature",signature);form.append("metadata",JSON.stringify(metadata.map(({name,description,attributes})=>({name,description,attributes}))));await appendPublishImages(form,selected);setChainStatus("AURA 正在上传图片与 Metadata 到 IPFS…");const response=await fetch("/api/publish",{method:"POST",body:form});const result=await response.json() as PublishResult&{error?:string;message?:string};if(!response.ok)throw new Error(result.message||result.error||"PUBLISH_FAILED");setPublished(result);setChainStatus(`${result.count} 件图片与 Metadata 已由 AURA 安全上传至 IPFS`);return result}catch(e){const message=e instanceof Error?e.message:"";setChainStatus(message.includes("UPLOAD_NOT_CONFIGURED")||message.includes("STORAGE_NOT_CONFIGURED")?"AURA IPFS 服务尚未配置，请联系平台管理员":message.includes("user rejected")||message.includes("ACTION_REJECTED")?"你已取消本次内容发布签名":message.includes("WRONG_CHAIN")?"网络不正确：仅支持 Robinhood Mainnet（4663）":message.includes("REMOTE_IMAGE")?"生成图片读取失败，请重新生成或稍后重试":"上传没有完成，请检查文件或稍后重试");return null}finally{setPublishing(false)}}
  function validatePublish(currentPublished=published){if(!isAddress(contractAddress)){setChainStatus("AURA 官方 Collection 合约尚未配置");return false}if(!currentPublished||currentPublished.tokenUris.length!==selected.length){setChainStatus("请先让 AURA 自动上传图片与 Metadata");return false}if(contractVersion==="2"&&!currentPublished.authorization){setChainStatus("本批次缺少 AURA Mint 授权，请重新发布素材");return false}if(!selected.length){setChainStatus("请先选择至少一件生成结果");return false}return true}
  function tokenUris(){return published?.tokenUris||[]}
  async function inspectMint(currentPublished=published){if(!wallet||!provider){openWallets();return null}if(!validatePublish(currentPublished))return null;setChecking(true);setMintQuote(null);try{if(!await ensureRobinhood())throw new Error("WRONG_CHAIN");const ethersProvider=new BrowserProvider(provider);const network=await ethersProvider.getNetwork();if(Number(network.chainId)!==ROBINHOOD_CHAIN_ID)throw new Error("WRONG_CHAIN");const code=await ethersProvider.getCode(contractAddress);if(code==="0x")throw new Error("NO_CONTRACT");const nft=new Contract(contractAddress,AURA_COLLECTION_ABI,ethersProvider);const total=BigInt(await nft.quoteMint(selected.length));const next={total};setMintQuote(next);setChainStatus(`发行准备完成：${selected.length} 件 NFT，Mint 金额 ${formatEther(total)} ETH，不含网络 Gas`);return next}catch(e){const message=e instanceof Error?e.message:"";setChainStatus(message.includes("WRONG_CHAIN")?"网络不正确：仅支持 Robinhood Mainnet（4663）":message.includes("NO_CONTRACT")?"该地址在 Robinhood Mainnet 上没有合约":"无法读取合约报价，请确认使用已验证的 AURA Collection 合约");return null}finally{setChecking(false)}}
  async function prepareMint(){const currentPublished=published||await publishAssets();if(currentPublished)await inspectMint(currentPublished)}
  async function mint(){if(!wallet||!provider){openWallets();return}if(!validatePublish())return;setMinting(true);setMintConfirmed(false);setTxHash("");try{if(!await ensureRobinhood())throw new Error("WRONG_CHAIN");const quote=await inspectMint();if(!quote)throw new Error("QUOTE_FAILED");const ethersProvider=new BrowserProvider(provider);const network=await ethersProvider.getNetwork();if(Number(network.chainId)!==ROBINHOOD_CHAIN_ID)throw new Error("WRONG_CHAIN");const signer=await ethersProvider.getSigner();const nft=new Contract(contractAddress,AURA_COLLECTION_ABI,signer);const authorization=published?.authorization;const tx=contractVersion==="2"&&authorization?await nft.mintBatchAuthorized(wallet,tokenUris(),authorization.deadline,authorization.signature,{value:quote.total}):await nft.mintBatch(wallet,tokenUris(),{value:quote.total});setTxHash(tx.hash);setChainStatus("批量 Mint 交易已提交，正在等待 Robinhood Mainnet 确认");await tx.wait();if(creationId)markCreationMinted(creationId,tx.hash,wallet);setMintConfirmed(true);setChainStatus(`${selected.length} 件 NFT 已在 Robinhood Mainnet 完成 Mint`)}catch(e){const message=e instanceof Error?e.message:"";if(!message.includes("QUOTE_FAILED"))setChainStatus(message.includes("WRONG_CHAIN")?"网络不正确：仅支持 Robinhood Mainnet（4663）":message.includes("authorization expired")?"Mint 授权已过期，请重新发布素材":message.includes("invalid authorization")?"AURA Mint 授权验证失败，请重新发布素材":message.includes("user rejected")||message.includes("ACTION_REJECTED")?"你已在钱包中取消交易":"Mint 未完成，请检查余额、合约状态、Metadata URI 和 Gas")}finally{setMinting(false)}}
  const activeOperation=publishing?{step:"01",eyebrow:"SECURE ASSET STORAGE",title:"正在将图片与 Metadata 写入 IPFS",detail:"请在钱包中确认内容发布签名。AURA 正在生成不可变的内容地址。"}:checking?{step:"02",eyebrow:"SMART CONTRACT VERIFICATION",title:"正在验证 Collection 合约与 Mint 金额",detail:"正在读取 Robinhood Mainnet 合约状态、网络与本批次报价。"}:minting?{step:"03",eyebrow:"ONCHAIN CONFIRMATION",title:"等待钱包签名与链上确认",detail:"交易将仅发送至 Robinhood Mainnet。请勿关闭页面或切换网络。"}:null;
  const mintPhase=mintConfirmed?"complete":!connected?"wallet":!mintQuote?"prepare":"mint";
  return <main className="studio-workspace"><SiteHeader/><section className="studio-top"><div><span>AURA CREATION ENGINE / PRODUCTION CONSOLE</span><h1>从创意主体到链上 Collection</h1><p>确定主体、扩展视觉、编排 Metadata，最后在 Robinhood Mainnet 完成发行。</p><div className="engine-capabilities"><i>SUBJECT LOCK</i><i>TRAIT ENGINE</i><i>IPFS METADATA</i><i>MAINNET MINT</i></div></div><b><i/> ROBINHOOD MAINNET · 4663</b></section>
    <nav className="studio-steps">{studioSteps.map(x=><button className={step===x[0]?"active":step>x[0]?"done":""} key={x[0]} onClick={()=>step>=x[0]&&setStep(x[0])}><i>{step>x[0]?"✓":x[0]}</i><span>{x[1]}</span></button>)}</nav>
    <section className="studio-stage">
      {activeOperation&&<div className="chain-operation" role="status" aria-live="polite"><div className="operation-orbit"><i/><i/><i/><b>{activeOperation.step}</b></div><div className="operation-copy"><small>{activeOperation.eyebrow}</small><strong>{activeOperation.title}</strong><p>{activeOperation.detail}</p><div className="operation-progress"><i/></div></div></div>}
      {!activeOperation&&mintConfirmed&&step===4&&<div className="transaction-ready"><i>✓</i><div><b>Mint 已完成，作品已写入 Robinhood Mainnet</b><small>{chainStatus}</small></div><a href="/history">查看我的链上作品与记录 →</a><span>ROBINHOOD MAINNET</span></div>}
      {step===1&&<div className="stage-input">
        <aside><span>01 / SUBJECT</span><h2>描述或上传主体</h2><div className="source-tabs"><button className={inputMode==="text"?"active":""} onClick={()=>setInputMode("text")}>文字描述</button><button className={inputMode==="upload"?"active":""} onClick={()=>setInputMode("upload")}>上传素材</button></div>{inputMode==="text"?<div className="source-description"><label>主体描述<textarea value={subjectDescription} onChange={e=>{setSubjectDescription(e.target.value);setSubjectConfirmed(false)}} maxLength={300} placeholder="描述角色、物体、外观和必须保留的识别特征"/><small>{subjectDescription.length}/300</small></label><button className="subject-generate" onClick={generateSubjects} disabled={!aiStatus||subjectRunning||!subjectDescription.trim()}>{!aiStatus?"正在连接图像引擎…":subjectRunning?(aiStatus.configured?`${aiStatus.provider} 正在生成 · ${subjectProgress}/1`:"正在生成演示主体…"):"生成 1 个主体"} <b>→</b></button>{subjectCandidates.length>0&&<><div className="subject-candidates" aria-label="主体候选方案">{subjectCandidates.map(candidate=><button className={chosenSubject===candidate.id?"selected":""} onClick={()=>{setChosenSubject(candidate.id);setSubjectConfirmed(false)}} key={candidate.id}><img src={candidate.url} alt="生成的主体预览"/><span>主体预览</span></button>)}</div><div className="subject-confirm"><span>{subjectConfirmed?"✓ 已确认主体，可继续生成系列":chosenSubject?"请确认是否以此主体扩展系列":"查看生成结果并选择主体"}</span><button onClick={confirmSubject} disabled={!chosenSubject||subjectConfirmed}>{subjectConfirmed?"已确认":"确认使用此主体"}</button></div></>}</div>:<label className="source-upload" style={{backgroundImage:`url(${source})`}}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/><b>更换图片</b><small>{fileName}</small></label>}<p>{inputMode==="text"?"先生成并确认一个主体，再以它为视觉基准扩展 NFT 系列。":"支持 PNG、JPG、WEBP。建议主体清晰、背景简单、分辨率不低于 1024px。"}</p></aside>
        <article><span>02 / DIRECTION</span><h2>描述系列生成要求</h2><div className={`ai-provider ${aiStatus?.configured?"online":"demo"}`}><i/><div><b>{aiStatus?.configured?`${aiStatus.provider} 图像引擎已连接`:"AI 图像引擎待配置"}</b><small>{aiStatus?.configured?`${aiStatus.model} · 真实生成与参考图编辑`:aiStatus===null?"正在检测服务状态…":"当前使用本地演示预览；配置服务商 API Key 后自动启用真实生成"}</small></div><em>{aiStatus?.configured?"LIVE":"DEMO"}</em></div>{aiError&&<div className="ai-error" role="alert"><b>生成未完成</b><span>{aiError}</span><button onClick={()=>setAiError("")}>×</button></div>}<label>创作要求<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={500}/><small>{prompt.length}/500</small></label><div className="studio-fields"><label>视觉方向<select value={style} onChange={e=>setStyle(e.target.value)}><option>3D 收藏品</option><option>PFP 头像</option><option>像素艺术</option><option>品牌插画</option></select></label><label>生成数量（最多 4 张）<select value={amount} onChange={e=>setAmount(e.target.value)}><option value="1">1 张</option><option value="2">2 张</option><option value="3">3 张</option><option value="4">4 张</option></select></label></div><button className="stage-primary" onClick={generate} disabled={!aiStatus||running||(inputMode==="text"&&!subjectConfirmed)}>{!aiStatus?"正在连接图像引擎…":running?(aiStatus.configured?`${aiStatus.provider} 正在生成 · ${generationProgress}/${amount}`:"正在生成演示系列…"):inputMode==="text"&&!subjectConfirmed?"请先生成并确认主体":`生成 ${amount} 张系列图片 →`}</button><p className="engine-note"><b>{aiStatus?.configured?"真实 AI 工作流：":"演示模式："}</b>{aiStatus?.configured?`${aiStatus.provider} 将锁定主体身份，再扩展服装、配件、材质、场景与稀有属性。本次最多生成 4 张可筛选图片，确认后进入 Metadata 与 Mint。`:"当前结果由浏览器本地生成，仅用于体验流程。管理员配置图片服务 API Key 后即可切换至真实 AI。"}</p></article>
      </div>}
      {step===2&&<div className="stage-results"><header><div><span>GENERATED OUTPUT</span><h2>选择要进入系列的图片</h2><p>点击图片进行选择或取消。已选择 {selected.length} / {results.length} 个方向。</p></div><button onClick={()=>saveZip(false)}>↓ 批量下载图片 ZIP</button></header><div>{results.map(x=><button className={x.selected?"selected":""} onClick={()=>toggle(x.id)} key={x.id}><img src={x.url} alt={`生成变体 ${x.id}`}/><span><i>{x.selected?"✓":"+"}</i> V{x.id} · {x.rarity}</span></button>)}</div><footer><button onClick={()=>setStep(1)}>← 返回修改</button><button className="stage-primary" disabled={!selected.length} onClick={()=>setStep(3)}>下一步：配置属性与 Metadata →</button></footer></div>}
      {step===3&&<div className="metadata-stage"><aside><span>COLLECTION SETTINGS</span><h2>命名与发行信息</h2><label>系列名称<input value={collection} onChange={e=>{setCollection(e.target.value);setPublished(null);setMintQuote(null)}}/></label><div className="studio-fields"><label>代号<input value={symbol} onChange={e=>{setSymbol(e.target.value.toUpperCase().slice(0,8));setPublished(null);setMintQuote(null)}}/></label><label>作品名称前缀<input value={itemName} onChange={e=>{setItemName(e.target.value);setPublished(null);setMintQuote(null)}}/></label></div><label>系列描述<textarea value={description} onChange={e=>{setDescription(e.target.value);setPublished(null);setMintQuote(null)}}/></label><label>稀有度模型<select value={rarity} onChange={e=>{setRarity(e.target.value);setPublished(null);setMintQuote(null)}}><option value="Balanced">均衡分布</option><option value="Collector">收藏型：稀有属性较少</option><option value="Game">游戏型：多等级属性</option></select></label><button className="package-btn" onClick={()=>saveZip(true)}>↓ 下载图片 + Metadata 发行包</button></aside><article><header><span>METADATA PREVIEW</span><b>{metadata.length} JSON FILES</b></header><pre>{JSON.stringify(metadata[0]||{},null,2)}</pre><div className="metadata-checks"><p><i>✓</i> 图片与 Token 编号一一对应</p><p><i>✓</i> 包含名称、描述、属性和稀有度</p><p><i>✓</i> 输出标准 JSON 与系列配置</p></div><footer><button onClick={()=>setStep(2)}>← 返回筛选</button><button className="stage-primary" onClick={()=>setStep(4)}>下一步：Robinhood 上链 →</button></footer></article></div>}
      {step===4&&<div className="mint-stage mint-console">
        <aside><span>COLLECTION REVIEW</span><div className="mint-review-title"><div><h2>{collection}</h2><small>{symbol} · {selected.length} ITEMS</small></div><b>READY</b></div><div className="mint-cover"><img src={selected[0]?.url||source} alt="系列封面"/><div><b>{selected.length} 件作品已通过筛选</b><small>图片、属性与 Metadata 已完成映射</small></div></div><div className="mint-preview-strip">{selected.slice(0,5).map(item=><img src={item.url} alt="" key={item.id}/>)}{selected.length>5&&<i>+{selected.length-5}</i>}</div><dl><div><dt>发行网络</dt><dd><i className="status-dot"/> Robinhood Mainnet</dd></div><div><dt>官方合集</dt><dd>AURA Official Collection</dd></div><div><dt>合约</dt><dd>{contractAddress?`${contractAddress.slice(0,8)}…${contractAddress.slice(-6)}`:"等待配置"}</dd></div><div><dt>平台服务费</dt><dd>0 ETH</dd></div><div><dt>资产存储</dt><dd>{published?`${published.count} items · IPFS`:"尚未发布"}</dd></div></dl><button className="mint-back" onClick={()=>setStep(3)}>← 返回 Metadata 设置</button></aside>
        <article><div className="mint-console-head"><div><span>ONCHAIN PUBLISHER</span><h2>发布到 Robinhood Mainnet</h2></div><b><i/> MAINNET · 4663</b></div><p>全程由你的钱包授权。AURA 负责存储与合约调用，不托管资产，也不收取平台服务费。</p><div className="mint-assurances"><span><i>01</i><b>内容签名</b><small>不消耗 Gas</small></span><span><i>02</i><b>Mint 签名</b><small>支付网络 Gas</small></span><span><i>0</i><b>平台费用</b><small>0 ETH</small></span></div><div className="mint-flow-list"><div className={published?"done":mintPhase==="wallet"||mintPhase==="prepare"?"active":""}><i>{published?"✓":"01"}</i><span><b>资产永久存储</b><small>{published?`${published.provider} · 已完成`:connected?"内容签名后自动上传":"等待连接钱包"}</small></span></div><div className={mintQuote?"done":mintPhase==="prepare"&&published?"active":""}><i>{mintQuote?"✓":"02"}</i><span><b>合约与费用验证</b><small>{mintQuote?`本批次 ${formatEther(mintQuote.total)} ETH` :published?"正在读取实时 Mint 金额":"上传完成后自动验证"}</small></span></div><div className={mintConfirmed?"done":mintPhase==="mint"?"active":""}><i>{mintConfirmed?"✓":"03"}</i><span><b>钱包签名并上链</b><small>{mintConfirmed?"Robinhood Mainnet 已确认":txHash?"交易已提交，等待区块确认":"一次签名完成整批 NFT Mint"}</small></span></div></div>
          <div className="mint-wallet-row"><div><i className={connected?"online":""}/><span><small>发行钱包</small><b>{connected?`${wallet.slice(0,8)}…${wallet.slice(-6)}`:"尚未连接"}</b></span></div><button onClick={openWallets}>{connected?"管理钱包":"连接钱包"}</button></div>
          {mintQuote&&<div className="mint-quote"><div><span>NFT Mint 金额</span><b>{formatEther(mintQuote.total)} ETH</b></div><div><span>AURA 平台服务费</span><b>0 ETH</b></div><div><span>钱包支付（不含 Gas）</span><b>{formatEther(mintQuote.total)} ETH</b></div></div>}
          <div className={`mint-status-panel ${mintConfirmed?"success":""}`}><i>{mintConfirmed?"✓":"i"}</i><span><b>{mintConfirmed?"链上发行已经完成":txHash?"交易等待确认":"当前状态"}</b><small>{chainStatus}</small></span></div>
          <div className="mint-primary-zone">{mintPhase==="wallet"?<button className="mint-unified-action" onClick={openWallets}>连接钱包，开始链上发行 <b>→</b></button>:mintPhase==="prepare"?<button className="mint-unified-action" onClick={prepareMint} disabled={publishing||checking}>{publishing?"正在上传图片与 Metadata…":checking?"正在验证官方合约与费用…":published?"重新验证发行配置":"准备链上发行"} <b>→</b></button>:mintPhase==="mint"?<button className="mint-unified-action mint-now" onClick={mint} disabled={minting||checking}>{minting?"等待钱包与链上确认…":`确认 Mint ${selected.length} 件 NFT`} <b>→</b></button>:<a className="mint-unified-action mint-complete" href="/history">查看已经上链的作品 <b>→</b></a>}</div>
          {txHash?<div className="mint-result-links"><a href={`${ROBINHOOD_EXPLORER}/tx/${txHash}`} target="_blank" rel="noreferrer">查看交易详情 ↗</a><a href="/history">打开我的链上记录 →</a></div>:<small className="mint-warning">钱包只会请求当前步骤所需的签名。最终 Gas 由 Robinhood 网络实时计算。</small>}
        </article>
      </div>}
    </section>
    {showMarketGuide&&mintConfirmed&&<div className="post-mint-market" role="dialog" aria-modal="true" aria-labelledby="post-mint-title">
      <section>
        <button className="post-mint-close" onClick={()=>setShowMarketGuide(false)} aria-label="关闭 OpenSea 上架引导">×</button>
        <div className="post-mint-visual"><div className="mint-success-ring"><i>✓</i><span/><span/></div><small>TRANSACTION CONFIRMED</small><b>ROBINHOOD<br/>MAINNET</b><code>{txHash?`${txHash.slice(0,10)}…${txHash.slice(-8)}`:"CONFIRMED"}</code></div>
        <div className="post-mint-copy">
          <span className="post-mint-kicker"><i/> MINT SUCCESS · NEXT STEP</span>
          <h2 id="post-mint-title">NFT 已成功 Mint。<br/>是否前往 <em>OpenSea</em> 上架？</h2>
          <p>你的 <strong>{selected.length} 件 NFT</strong> 已归属当前钱包。OpenSea 已支持 Robinhood Chain，连接同一钱包后即可查看资产并设置售价。</p>
          <div className="market-guide-steps"><article><i>1</i><span><b>连接同一钱包</b><small>使用本次 Mint 的 {wallet?`${wallet.slice(0,7)}…${wallet.slice(-5)}`:"钱包"}</small></span></article><article><i>2</i><span><b>找到已 Mint 的 NFT</b><small>若图片尚未出现，请等待市场完成 Metadata 索引</small></span></article><article><i>3</i><span><b>设置价格并签名挂牌</b><small>售价、版税与市场费用以 OpenSea 页面为准</small></span></article></div>
          <div className="post-mint-actions"><a className="market-primary" href="https://opensea.io/account" target="_blank" rel="noopener noreferrer"><span className="opensea-mark">OS</span><b>前往 OpenSea 上架</b><i>↗</i></a><a href="/history">先查看我的链上作品 <b>→</b></a></div>
          <div className="post-mint-links">{txHash&&<a href={`${ROBINHOOD_EXPLORER}/tx/${txHash}`} target="_blank" rel="noreferrer">验证本次交易 ↗</a>}<button onClick={()=>setShowMarketGuide(false)}>暂不上架，留在此页</button></div>
          <small className="market-disclaimer">OpenSea 为第三方市场。AURA 不自动替你挂牌，也不托管 NFT；最终上架操作和签名由你的钱包完成。</small>
        </div>
      </section>
    </div>}
  </main>
}
